# used for creating test index for elasticsearch
index: deployment-dev-index
creation:
    settings:
        refresh_interval: 50ms
        analysis:
            analyzer:
                my_analyzer:
                    type: custom
                    tokenizer: standard
                    filter:
                        - asciifolding
                        - lowercase
                        - my_stopword_filter
                        - porter_stem
            filter:
                my_stopword_filter:
                    type: stop
                    stopwords_path: qa_backend_config/stopwords.txt
    mappings:
        properties:
            text:
                type: text
                analyzer: my_analyzer
