# used for creating test index for elasticsearch
index: deployment-index
creation:
    settings:
        refresh_interval: 50ms
        analysis:
            analyzer:
                my_analyzer:
                    type: custom
                    tokenizer: standard
                    filter:
                        - asciifolding
                        - lowercase
                        - porter_stem
    mappings:
        properties:
            text:
                type: text
                analyzer: my_analyzer
